version: '2.4'
services:
    serv:
        build: ./
        logging:
            options:
                max-file: 3
                max-size: 10m
        ports:
            - "5000:5000"
        environment:
            FAISS_GRPC_LOG_LEVEL: "INFO"