version: "2.4"
x-log: &default_log
  driver: json-file
  options:
    max-siz: 10m
    max-file: 3

services:
  faiss_grpc:
    image: hsz1273327/faiss_grpc:amd64-0.0.0
    logging:
      <<: *default_log
    environment:
      FAISS_GRPC_LOG_LEVEL: DEBUG
    command:
      - python
      - app
    ports:
      - 5000:5000
    cpus: 0.5
    mem_limit: 256m
    mem_reservation: 64m
    restart: on-failure
