// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: faiss_rpc.proto
#ifndef GRPC_faiss_5frpc_2eproto__INCLUDED
#define GRPC_faiss_5frpc_2eproto__INCLUDED

#include "faiss_rpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace hszofficial {
namespace faiss_rpc {

class FaissRpc final {
 public:
  static constexpr char const* service_full_name() {
    return "hszofficial.faiss_rpc.FaissRpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status search(::grpc::ClientContext* context, const ::hszofficial::faiss_rpc::Query& request, ::hszofficial::faiss_rpc::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hszofficial::faiss_rpc::Response>> Asyncsearch(::grpc::ClientContext* context, const ::hszofficial::faiss_rpc::Query& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hszofficial::faiss_rpc::Response>>(AsyncsearchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hszofficial::faiss_rpc::Response>> PrepareAsyncsearch(::grpc::ClientContext* context, const ::hszofficial::faiss_rpc::Query& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hszofficial::faiss_rpc::Response>>(PrepareAsyncsearchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>> batch_search(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>>(batch_searchRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>> Asyncbatch_search(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>>(Asyncbatch_searchRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>> PrepareAsyncbatch_search(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>>(PrepareAsyncbatch_searchRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void search(::grpc::ClientContext* context, const ::hszofficial::faiss_rpc::Query* request, ::hszofficial::faiss_rpc::Response* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hszofficial::faiss_rpc::Response>* AsyncsearchRaw(::grpc::ClientContext* context, const ::hszofficial::faiss_rpc::Query& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hszofficial::faiss_rpc::Response>* PrepareAsyncsearchRaw(::grpc::ClientContext* context, const ::hszofficial::faiss_rpc::Query& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>* batch_searchRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>* Asyncbatch_searchRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>* PrepareAsyncbatch_searchRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status search(::grpc::ClientContext* context, const ::hszofficial::faiss_rpc::Query& request, ::hszofficial::faiss_rpc::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hszofficial::faiss_rpc::Response>> Asyncsearch(::grpc::ClientContext* context, const ::hszofficial::faiss_rpc::Query& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hszofficial::faiss_rpc::Response>>(AsyncsearchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hszofficial::faiss_rpc::Response>> PrepareAsyncsearch(::grpc::ClientContext* context, const ::hszofficial::faiss_rpc::Query& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hszofficial::faiss_rpc::Response>>(PrepareAsyncsearchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>> batch_search(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>>(batch_searchRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>> Asyncbatch_search(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>>(Asyncbatch_searchRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>> PrepareAsyncbatch_search(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>>(PrepareAsyncbatch_searchRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void search(::grpc::ClientContext* context, const ::hszofficial::faiss_rpc::Query* request, ::hszofficial::faiss_rpc::Response* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::hszofficial::faiss_rpc::Response>* AsyncsearchRaw(::grpc::ClientContext* context, const ::hszofficial::faiss_rpc::Query& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::hszofficial::faiss_rpc::Response>* PrepareAsyncsearchRaw(::grpc::ClientContext* context, const ::hszofficial::faiss_rpc::Query& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>* batch_searchRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>* Asyncbatch_searchRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::hszofficial::faiss_rpc::BatchQuery, ::hszofficial::faiss_rpc::BatchResponse>* PrepareAsyncbatch_searchRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_search_;
    const ::grpc::internal::RpcMethod rpcmethod_batch_search_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status search(::grpc::ServerContext* context, const ::hszofficial::faiss_rpc::Query* request, ::hszofficial::faiss_rpc::Response* response);
    virtual ::grpc::Status batch_search(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::hszofficial::faiss_rpc::BatchResponse, ::hszofficial::faiss_rpc::BatchQuery>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_search() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status search(::grpc::ServerContext* context, const ::hszofficial::faiss_rpc::Query* request, ::hszofficial::faiss_rpc::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsearch(::grpc::ServerContext* context, ::hszofficial::faiss_rpc::Query* request, ::grpc::ServerAsyncResponseWriter< ::hszofficial::faiss_rpc::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_batch_search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_batch_search() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_batch_search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_search(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::hszofficial::faiss_rpc::BatchResponse, ::hszofficial::faiss_rpc::BatchQuery>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestbatch_search(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::hszofficial::faiss_rpc::BatchResponse, ::hszofficial::faiss_rpc::BatchQuery>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_search<WithAsyncMethod_batch_search<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_search() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status search(::grpc::ServerContext* context, const ::hszofficial::faiss_rpc::Query* request, ::hszofficial::faiss_rpc::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_batch_search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_batch_search() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_batch_search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_search(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::hszofficial::faiss_rpc::BatchResponse, ::hszofficial::faiss_rpc::BatchQuery>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_search() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status search(::grpc::ServerContext* context, const ::hszofficial::faiss_rpc::Query* request, ::hszofficial::faiss_rpc::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsearch(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_batch_search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_batch_search() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_batch_search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_search(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::hszofficial::faiss_rpc::BatchResponse, ::hszofficial::faiss_rpc::BatchQuery>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestbatch_search(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_search() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::hszofficial::faiss_rpc::Query, ::hszofficial::faiss_rpc::Response>(std::bind(&WithStreamedUnaryMethod_search<BaseClass>::Streamedsearch, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status search(::grpc::ServerContext* context, const ::hszofficial::faiss_rpc::Query* request, ::hszofficial::faiss_rpc::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedsearch(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::hszofficial::faiss_rpc::Query,::hszofficial::faiss_rpc::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_search<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_search<Service > StreamedService;
};

}  // namespace faiss_rpc
}  // namespace hszofficial


#endif  // GRPC_faiss_5frpc_2eproto__INCLUDED
