# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faiss_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='faiss_rpc.proto',
  package='hszofficial.faiss_rpc',
  syntax='proto3',
  serialized_options=b'Z\025hszofficial_faiss_rpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x66\x61iss_rpc.proto\x12\x15hszofficial.faiss_rpc\"\x17\n\x03Vec\x12\x10\n\x08\x65lements\x18\x01 \x03(\x02\"W\n\x05Query\x12\x14\n\x0ctarget_index\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\x12-\n\tquery_vec\x18\x03 \x01(\x0b\x32\x1a.hszofficial.faiss_rpc.Vec\"o\n\nBatchQuery\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12\x14\n\x0ctarget_index\x18\x02 \x01(\t\x12\t\n\x01k\x18\x03 \x01(\x05\x12.\n\nquery_vecs\x18\x04 \x03(\x0b\x32\x1a.hszofficial.faiss_rpc.Vec\"~\n\x0eResponseStatus\x12:\n\x06status\x18\x01 \x01(\x0e\x32*.hszofficial.faiss_rpc.ResponseStatus.Stat\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x04Stat\x12\x0b\n\x07SUCCEED\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\"\x14\n\x04TopK\x12\x0c\n\x04rank\x18\x01 \x03(\x03\"n\n\x08Response\x12\x35\n\x06status\x18\x01 \x01(\x0b\x32%.hszofficial.faiss_rpc.ResponseStatus\x12+\n\x06result\x18\x02 \x01(\x0b\x32\x1b.hszofficial.faiss_rpc.TopK\"\x85\x01\n\rBatchResponse\x12\x35\n\x06status\x18\x01 \x01(\x0b\x32%.hszofficial.faiss_rpc.ResponseStatus\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\t\x12+\n\x06result\x18\x03 \x03(\x0b\x32\x1b.hszofficial.faiss_rpc.TopK2\xb4\x01\n\x08\x46\x61issRpc\x12I\n\x06search\x12\x1c.hszofficial.faiss_rpc.Query\x1a\x1f.hszofficial.faiss_rpc.Response\"\x00\x12]\n\x0c\x62\x61tch_search\x12!.hszofficial.faiss_rpc.BatchQuery\x1a$.hszofficial.faiss_rpc.BatchResponse\"\x00(\x01\x30\x01\x42\x17Z\x15hszofficial_faiss_rpcb\x06proto3'
)



_RESPONSESTATUS_STAT = _descriptor.EnumDescriptor(
  name='Stat',
  full_name='hszofficial.faiss_rpc.ResponseStatus.Stat',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCEED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=364,
  serialized_end=395,
)
_sym_db.RegisterEnumDescriptor(_RESPONSESTATUS_STAT)


_VEC = _descriptor.Descriptor(
  name='Vec',
  full_name='hszofficial.faiss_rpc.Vec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='hszofficial.faiss_rpc.Vec.elements', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=65,
)


_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='hszofficial.faiss_rpc.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_index', full_name='hszofficial.faiss_rpc.Query.target_index', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='k', full_name='hszofficial.faiss_rpc.Query.k', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query_vec', full_name='hszofficial.faiss_rpc.Query.query_vec', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=154,
)


_BATCHQUERY = _descriptor.Descriptor(
  name='BatchQuery',
  full_name='hszofficial.faiss_rpc.BatchQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='batch_id', full_name='hszofficial.faiss_rpc.BatchQuery.batch_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_index', full_name='hszofficial.faiss_rpc.BatchQuery.target_index', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='k', full_name='hszofficial.faiss_rpc.BatchQuery.k', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query_vecs', full_name='hszofficial.faiss_rpc.BatchQuery.query_vecs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=267,
)


_RESPONSESTATUS = _descriptor.Descriptor(
  name='ResponseStatus',
  full_name='hszofficial.faiss_rpc.ResponseStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='hszofficial.faiss_rpc.ResponseStatus.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='hszofficial.faiss_rpc.ResponseStatus.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSESTATUS_STAT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=395,
)


_TOPK = _descriptor.Descriptor(
  name='TopK',
  full_name='hszofficial.faiss_rpc.TopK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rank', full_name='hszofficial.faiss_rpc.TopK.rank', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=417,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='hszofficial.faiss_rpc.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='hszofficial.faiss_rpc.Response.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='hszofficial.faiss_rpc.Response.result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=529,
)


_BATCHRESPONSE = _descriptor.Descriptor(
  name='BatchResponse',
  full_name='hszofficial.faiss_rpc.BatchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='hszofficial.faiss_rpc.BatchResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_id', full_name='hszofficial.faiss_rpc.BatchResponse.batch_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='hszofficial.faiss_rpc.BatchResponse.result', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=665,
)

_QUERY.fields_by_name['query_vec'].message_type = _VEC
_BATCHQUERY.fields_by_name['query_vecs'].message_type = _VEC
_RESPONSESTATUS.fields_by_name['status'].enum_type = _RESPONSESTATUS_STAT
_RESPONSESTATUS_STAT.containing_type = _RESPONSESTATUS
_RESPONSE.fields_by_name['status'].message_type = _RESPONSESTATUS
_RESPONSE.fields_by_name['result'].message_type = _TOPK
_BATCHRESPONSE.fields_by_name['status'].message_type = _RESPONSESTATUS
_BATCHRESPONSE.fields_by_name['result'].message_type = _TOPK
DESCRIPTOR.message_types_by_name['Vec'] = _VEC
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['BatchQuery'] = _BATCHQUERY
DESCRIPTOR.message_types_by_name['ResponseStatus'] = _RESPONSESTATUS
DESCRIPTOR.message_types_by_name['TopK'] = _TOPK
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['BatchResponse'] = _BATCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vec = _reflection.GeneratedProtocolMessageType('Vec', (_message.Message,), {
  'DESCRIPTOR' : _VEC,
  '__module__' : 'faiss_rpc_pb2'
  # @@protoc_insertion_point(class_scope:hszofficial.faiss_rpc.Vec)
  })
_sym_db.RegisterMessage(Vec)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'faiss_rpc_pb2'
  # @@protoc_insertion_point(class_scope:hszofficial.faiss_rpc.Query)
  })
_sym_db.RegisterMessage(Query)

BatchQuery = _reflection.GeneratedProtocolMessageType('BatchQuery', (_message.Message,), {
  'DESCRIPTOR' : _BATCHQUERY,
  '__module__' : 'faiss_rpc_pb2'
  # @@protoc_insertion_point(class_scope:hszofficial.faiss_rpc.BatchQuery)
  })
_sym_db.RegisterMessage(BatchQuery)

ResponseStatus = _reflection.GeneratedProtocolMessageType('ResponseStatus', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESTATUS,
  '__module__' : 'faiss_rpc_pb2'
  # @@protoc_insertion_point(class_scope:hszofficial.faiss_rpc.ResponseStatus)
  })
_sym_db.RegisterMessage(ResponseStatus)

TopK = _reflection.GeneratedProtocolMessageType('TopK', (_message.Message,), {
  'DESCRIPTOR' : _TOPK,
  '__module__' : 'faiss_rpc_pb2'
  # @@protoc_insertion_point(class_scope:hszofficial.faiss_rpc.TopK)
  })
_sym_db.RegisterMessage(TopK)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'faiss_rpc_pb2'
  # @@protoc_insertion_point(class_scope:hszofficial.faiss_rpc.Response)
  })
_sym_db.RegisterMessage(Response)

BatchResponse = _reflection.GeneratedProtocolMessageType('BatchResponse', (_message.Message,), {
  'DESCRIPTOR' : _BATCHRESPONSE,
  '__module__' : 'faiss_rpc_pb2'
  # @@protoc_insertion_point(class_scope:hszofficial.faiss_rpc.BatchResponse)
  })
_sym_db.RegisterMessage(BatchResponse)


DESCRIPTOR._options = None

_FAISSRPC = _descriptor.ServiceDescriptor(
  name='FaissRpc',
  full_name='hszofficial.faiss_rpc.FaissRpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=668,
  serialized_end=848,
  methods=[
  _descriptor.MethodDescriptor(
    name='search',
    full_name='hszofficial.faiss_rpc.FaissRpc.search',
    index=0,
    containing_service=None,
    input_type=_QUERY,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='batch_search',
    full_name='hszofficial.faiss_rpc.FaissRpc.batch_search',
    index=1,
    containing_service=None,
    input_type=_BATCHQUERY,
    output_type=_BATCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FAISSRPC)

DESCRIPTOR.services_by_name['FaissRpc'] = _FAISSRPC

# @@protoc_insertion_point(module_scope)
